version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: megatrip
      MYSQL_USER: ${MYSQL_USER:-megatrip_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - megatrip-network

  # Streamlit Application Service
  web:
    image: registry.yourdomain.com/megatrip:latest
    platform: linux/amd64
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER:-megatrip_user}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: megatrip
    ports:
      - "8501:8501"
    depends_on:
      - db
    networks:
      - megatrip-network

volumes:
  mysql_data:

networks:
  megatrip-network:
    driver: bridge